using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//TO-DO 
//CREATE A SCRIPT WITH DIFERENT TYPES OF MOVEMENT

public class PlayerMovement : MonoBehaviour
{

    private float speed;
    [HideInInspector]
    public  Vector2 movement;
    private Rigidbody2D rb;

    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
    }

    // Update is called once per frame
     void Update()
    {
        speed = GetComponent<PlayerParameters>().speed;
        movement.x = Input.GetAxisRaw("Horizontal");
        movement.y = Input.GetAxisRaw("Vertical");

    }
    void FixedUpdate()
    {
        rb.MovePosition(rb.position + movement * speed * Time.fixedDeltaTime);

    }
    
        
    
}
